### PR TITLE
Add custom $parent_id

### PR DESCRIPTION
**Pull request by ghost**
Change read me and composer

### CODE REVIEW

**Comment by sdebacker** [comment]
I don't want typicms/nestablecollection be changed to austerussian/nestablecollection.

**Comment by sdebacker** [comment]
But i’m open for the possibility of changing the parent_id.

**Comment by ghost** [comment]
Sorry, I'm just learning and not quite understand what I was doing :). If you do not mind adding vobavit opportunity to change the parent_id, do it. And what do I need to do?

**Comment by ghost** [comment]
I would just make for yourself a package with the necessary changes. Maybe something I did wrong.

**Pull request closed without merging**
